/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad_1;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
      
         initComponents();
        //centrar 
        this.setLocationRelativeTo(null);
        //set iconos
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/menu.png"));
        this.setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductosBtn2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CategoriaBtn1 = new javax.swing.JButton();
        VendedoresBtn2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProductosBtn = new javax.swing.JButton();
        VendedoresBtn = new javax.swing.JButton();
        CategoriaBtn = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú");

        jLabel5.setText("jLabel5");

        ProductosBtn2.setBackground(new java.awt.Color(255, 255, 255));
        ProductosBtn2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ProductosBtn2.setText("Productos");
        ProductosBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosBtn2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Listas");

        CategoriaBtn1.setBackground(new java.awt.Color(255, 255, 255));
        CategoriaBtn1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CategoriaBtn1.setText("Categoria");
        CategoriaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaBtn1ActionPerformed(evt);
            }
        });

        VendedoresBtn2.setBackground(new java.awt.Color(255, 255, 255));
        VendedoresBtn2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        VendedoresBtn2.setText("Vendedores");
        VendedoresBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedoresBtn2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar");

        ProductosBtn.setBackground(new java.awt.Color(255, 255, 255));
        ProductosBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ProductosBtn.setText("Productos");
        ProductosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosBtnActionPerformed(evt);
            }
        });

        VendedoresBtn.setBackground(new java.awt.Color(255, 255, 255));
        VendedoresBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        VendedoresBtn.setText("Vendedores");
        VendedoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedoresBtnActionPerformed(evt);
            }
        });

        CategoriaBtn.setBackground(new java.awt.Color(255, 255, 255));
        CategoriaBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CategoriaBtn.setText("Categoria");
        CategoriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaBtnActionPerformed(evt);
            }
        });

        jLabel_close.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xmark.png"))); // NOI18N
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.setOpaque(true);
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menú");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CategoriaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VendedoresBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(ProductosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_close)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ProductosBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CategoriaBtn)
                .addGap(18, 18, 18)
                .addComponent(VendedoresBtn)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosBtnActionPerformed
        // TODO add your handling code here:
        Productos ss = new Productos();
        ss.setVisible(true);
        
    }//GEN-LAST:event_ProductosBtnActionPerformed

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // Cierra el programa
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void VendedoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedoresBtnActionPerformed
        // TODO add your handling code here:
        Vendedor sss = new  Vendedor();
        sss.setVisible(true);
    }//GEN-LAST:event_VendedoresBtnActionPerformed

    private void CategoriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaBtnActionPerformed
        // TODO add your handling code here:
         Categoria sssa = new  Categoria();
        sssa.setVisible(true);
    }//GEN-LAST:event_CategoriaBtnActionPerformed

    private void VendedoresBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedoresBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendedoresBtn2ActionPerformed

    private void ProductosBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosBtn2ActionPerformed

    private void CategoriaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoriaBtn;
    private javax.swing.JButton CategoriaBtn1;
    private javax.swing.JButton ProductosBtn;
    private javax.swing.JButton ProductosBtn2;
    private javax.swing.JButton VendedoresBtn;
    private javax.swing.JButton VendedoresBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    static class Lista_Productos {

        static boolean agregarProducto(String id, String nombre, String Cantidad) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Lista_Productos() {
        }
    }
}
